/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyHeader: typeof import('./../src/components/MyHeader.vue')['default']
    MySidebar: typeof import('./../src/components/MySidebar.vue')['default']
    MySlides: typeof import('./../src/components/MySlides.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
